version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 3
    target-branch: "develop"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@sentry/*"
      - dependency-name: "*eslint*"
      - dependency-name: "@types/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"