app = "lounasbotti-disec"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/builder:22"

  [build.args]
    NODE_ENV = "production"

[deploy]
  strategy = "rolling"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "15s"
    restart_limit = 2
    timeout = "2s"

  [[services.http_checks]]
    grace_period = "15s"
    interval = 60000
    method = "get"
    path = "/health-check"
    protocol = "http"
    restart_limit = 2
    timeout = 8000
    tls_skip_verify = false