# fly.toml app configuration file generated for lounasbotti-disec on 2023-06-04T16:04:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lounasbotti-disec"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
  strategy = "rolling"

[env]
  NODE_ENV = "production"
  
[[restart]]
  policy = "always"
  retries = 10

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = ["tls"]
  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "15s"
    restart_limit = 2

  [[services.http_checks]]
    interval = "1m0s"
    timeout = "8s"
    grace_period = "15s"
    restart_limit = 2
    method = "get"
    path = "/health-check"
    protocol = "http"
