name: "Run ESLint"
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        check-latest: true
        cache: "npm"
    - name: npm
      run: npm install --only=dev
    - name: lint
      run: npm run lint