name: "Run ESLint"
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: "22"
        check-latest: true
        cache: "npm"
    - name: npm
      run: npm install -D --no-audit --no-fund
    - name: lint
      run: npm run lint